import Foundation
import AppKit
import Telemetry

/// The four exports that can be attached to a helpdesk email.
enum ExportKind: String, CaseIterable, Identifiable {
    case networks, telemetry, snapshot, annotations
    var id: String { rawValue }
    var displayName: String {
        switch self {
        case .networks:    return "Nearby Networks (CSV)"
        case .telemetry:   return "Telemetry (CSV)"
        case .snapshot:    return "Snapshot (JSON)"
        case .annotations: return "Annotations (CSV)"
        }
    }
    var fileName: String {
        switch self {
        case .networks:    return "oncillascope-networks.csv"
        case .telemetry:   return "oncillascope-telemetry.csv"
        case .snapshot:    return "oncillascope-snapshot.json"
        case .annotations: return "oncillascope-annotations.csv"
        }
    }
}

struct EmailComposeResult {
    let attached: [String]
    let skipped: [String]
    let usedFallback: Bool
}

enum EmailExporter {
    /// Bytes for a kind, or nil if there's nothing meaningful to attach (skip it).
    @MainActor
    private static func data(for kind: ExportKind,
                             model: AppModel, annotations: AnnotationStore) -> Data? {
        switch kind {
        case .networks:
            guard !model.networks.isEmpty else { return nil }
            return Exporter.networksCSV(model.networks).data(using: .utf8)
        case .telemetry:
            guard !model.samples.isEmpty else { return nil }
            return Exporter.samplesCSV(model.samples).data(using: .utf8)
        case .snapshot:
            return try? Exporter.json(model.currentSnapshot())
        case .annotations:
            guard !annotations.items.isEmpty else { return nil }
            return annotations.annotationsCSV().data(using: .utf8)
        }
    }

    @MainActor
    static func compose(recipient: String, kinds: Set<ExportKind>,
                        model: AppModel, annotations: AnnotationStore) -> EmailComposeResult {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("oncillascope-email-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        var urls: [URL] = []
        var attached: [String] = [], skipped: [String] = []
        for kind in ExportKind.allCases where kinds.contains(kind) {
            guard let data = data(for: kind, model: model, annotations: annotations) else {
                skipped.append(kind.displayName); continue
            }
            let url = dir.appendingPathComponent(kind.fileName)
            do { try data.write(to: url); urls.append(url); attached.append(kind.displayName) }
            catch { skipped.append(kind.displayName) }
        }

        let host = ProcessInfo.processInfo.hostName
        let subject = "Oncillascope export — \(host)"
        let body = "Attached: \(attached.isEmpty ? "(none)" : attached.joined(separator: ", ")). " +
                   "Generated by Oncillascope on \(host)."

        let items: [Any] = [body as NSString] + urls
        if let service = NSSharingService(named: .composeEmail), service.canPerform(withItems: items) {
            service.recipients = [recipient]
            service.subject = subject
            service.perform(withItems: items)
            return EmailComposeResult(attached: attached, skipped: skipped, usedFallback: false)
        }

        // Fallback: no Mail client configured. Open a pre-addressed mailto (no attachment)
        // and reveal the files so the user can attach them manually.
        let enc = subject.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? ""
        if let mailto = URL(string: "mailto:\(recipient)?subject=\(enc)") {
            NSWorkspace.shared.open(mailto)
        }
        if !urls.isEmpty { NSWorkspace.shared.activateFileViewerSelecting(urls) }
        return EmailComposeResult(attached: attached, skipped: skipped, usedFallback: true)
    }
}
